version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    depends_on:
      - mongo
      - redis
    networks:
      - appnet

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - appnet

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - appnet
  
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

networks:
  appnet:
    driver: bridge