version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - appnet

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - appnet

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge